spring.application.name=backend
server.port=8081

# Conexão direta com o MongoDB sem usuário e sem senha
spring.mongodb.uri=mongodb://localhost:27017/zatt_db

# Conexão direta com o MongoDB sem usuário e sem senha
spring.data.mongodb.uri=mongodb://localhost:27017/zatt_db


# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Arquivos estáticos (CSS, JS, imagens)
spring.web.resources.static-locations=classpath:/static/